# Docker Compose Base
version : '3'
services:

        services:
                build:
                        context: .
                        dockerfile: dockerfiles/flask/Dockerfile
                image: modana-wallet-services