# Docker Compose for Dev Environments 
version : '3'
services:

        flask:
                image: modana-wallet-services
                entrypoint: ./scripts/build-dev.sh
                env_file: env/dev.env
                ports:
                - 5000:5000
                depends_on:
                - postgres
                - rabbitmq
                volumes:
                - "./:/app"
                
        postgres:
                env_file: env/dev.env
                build:
                        context: dockerfiles/postgres/
                ports:
                - 5432:5432
        
        rabbitmq:
                env_file: env/dev.env
                build:
                        context: dockerfiles/rabbitmq/
                ports:
                - 15000:15672

        celery:
                env_file: env/dev.env
                image: modana-wallet-services
                entrypoint: make bank-worker
                depends_on:
                - rabbitmq
                - postgres

        celery2:
                env_file: env/dev.env
                image: modana-wallet-services
                entrypoint: make transaction-worker
                depends_on:
                - rabbitmq
                - postgres

        celery3:
                env_file: env/dev.env
                image: modana-wallet-services
                entrypoint: make payment-worker
                depends_on:
                - rabbitmq
                - postgres

        flower:
                env_file: env/dev.env
                image: mher/flower
                ports:
                - 5555:5555
                depends_on:
                - rabbitmq

        grpc:
                entrypoint: ./start.sh
                image: modana-wallet-grpc
                env_file: env/dev.env
                ports:
                - 5001:5001
                depends_on:
                - flask

        callback:
                entrypoint: ./start.sh
                image: modana-va-fake-grpc
                environment: 
                - GRPC_PORT=10000
                ports:
                - 10000:10000
                depends_on:
                - flask