# Docker Compose Production Environments 
version : '3'
services:

        flask:
                image: modana-wallet-api
                entrypoint: ./build-prod.sh 
                environment:
                - DB_USERNAME=modana
                - DB_PASSWORD=password
                - DB_HOSTNAME=postgres
                - DB_NAME=db_wallet
                - ENVIRONMENT=prod
                - HOST=0.0.0.0
                ports:
                - 5000:5000
                depends_on:
                - postgres
                links:
                - postgres
                restart: always

                
        postgres:
                image: postgres:alpine
                environment:
                - POSTGRES_USER=modana
                - POSTGRES_PASSWORD=password
                - POSTGRES_DB=db_wallet_dev
                volumes:
                - "db_volume:/var/lib/postgresql/data"
                ports:
                - 5432:5432

        nginx:
                build:
                        context: dockerfiles/nginx/
                ports:
                - 5000:80
                depends_on:
                - flask

volumes:
        db_volume:
