# Docker Compose Production Environments 
version : '3'
services:

        flask:
                env_file: env/${ENV}.env
                build:
                        context: .
                        dockerfile: dockerfiles/flask/Dockerfile
                        args:
                                dependencies: requirements-${ENV}
                image: modana-wallet-services
                entrypoint: ./scripts/build-prod.sh
                depends_on:
                - postgres
                - rabbitmq
                restart: unless-stopped
                ports:
                - ${APP_PORT}:6000
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        postgres:
                env_file: env/${ENV}.env
                image: postgres:alpine
                volumes:
                - "prod_volume:/var/lib/postgresql/data"
                restart: unless-stopped
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        rabbitmq:
                env_file: env/${ENV}.env
                image: rabbitmq:3-management
                restart: unless-stopped
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        celery:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make bank-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        celery2:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make transaction-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        celery3:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make payment-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        celery4:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make utility-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        celery5:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make logging-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"
        
        scheduler:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make beat
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"

        flower:
                env_file: env/${ENV}.env
                image: mher/flower
                depends_on:
                - rabbitmq
                ports:
                - 6555:5555
                restart: unless-stopped
                
volumes:
        prod_volume:
