# Docker Compose Production Environments 
version : '3'
services:

        flask:
                env_file: env/${ENV}.env
                build:
                        context: .
                        dockerfile: dockerfiles/flask/Dockerfile
                image: modana-wallet-services
                entrypoint: ./scripts/build-prod.sh
                depends_on:
                - postgres
                - rabbitmq
                restart: always
                ports:
                - ${APP_PORT}:6000

        postgres:
                env_file: env/${ENV}.env
                build:
                        context: dockerfiles/postgres/
                volumes:
                - "db_volume:/var/lib/postgresql/data"
                restart: always

        rabbitmq:
                env_file: env/${ENV}.env
                build:
                        context: dockerfiles/rabbitmq/
                restart: always

        celery:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make bank-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: always

        celery2:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make transaction-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: always

        celery3:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make payment-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: always

        celery4:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make utility-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: always

        flower:
                env_file: env/${ENV}.env
                image: mher/flower
                depends_on:
                - rabbitmq
                ports:
                - 6555:5555
                restart: always
volumes:
        db_volume:
