# Docker Compose Production Environments 
version : '3'
services:

        flask:
                env_file: env/${ENV}.env
                build:
                        context: .
                        dockerfile: dockerfiles/flask/Dockerfile
                        args:
                                dependencies: requirements-${ENV}
                image: modana-wallet-services
                entrypoint: ./scripts/build-dev.sh
                depends_on:
                - postgres
                - rabbitmq
                restart: unless-stopped
                ports:
                - ${APP_PORT}:5000

        postgres:
                env_file: env/${ENV}.env
                image: postgres
                volumes:
                - "db_volume:/var/lib/postgresql/data"
                restart: unless-stopped

        rabbitmq:
                env_file: env/${ENV}.env
                image: rabbitmq:3-management
                restart: unless-stopped

        celery:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make bank-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped

        celery2:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make transaction-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped

        celery3:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make payment-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped

        celery4:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make utility-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped

        celery5:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make logging-worker
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped

        beat:
                env_file: env/${ENV}.env
                image: modana-wallet-services
                entrypoint: make beat
                depends_on:
                - rabbitmq
                - postgres
                restart: unless-stopped

        flower:
                env_file: env/${ENV}.env
                image: mher/flower
                depends_on:
                - rabbitmq
                ports:
                - 6555:5555
                restart: unless-stopped

        grpc:
                env_file: env/${ENV}.env
                image: modana-wallet-grpc
                entrypoint: ./start.sh
                depends_on:
                - flask
                ports:
                - 6001:6001
                restart: unless-stopped

        callback:
                image: modana-va-fake-grpc
                entrypoint: ./start.sh
                environment: 
                - GRPC_PORT=10000
                depends_on:
                - flask
                ports:
                - 10000:10000
                restart: unless-stopped

volumes:
        db_volume:
