# Docker Compose Production Environments 
version : '3'
services:

        flask:
                image: modana-wallet-services
                entrypoint: ./scripts/build-prod.sh
                env_file: env/prod.env
                depends_on:
                - postgres
                - rabbitmq
                restart: always
                ports:
                - 6000:5000

        postgres:
                build:
                        context: dockerfiles/postgres/
                env_file: env/prod.env
                volumes:
                - "db_volume:/var/lib/postgresql/data"
                restart: always

        rabbitmq:
                build:
                        context: dockerfiles/rabbitmq/
                env_file: env/prod.env
                ports:
                - 15000:15672

        celery:
                env_file: env/prod.env
                image: modana-wallet-services
                entrypoint: make worker
                depends_on:
                - rabbitmq
                - postgres

        flower:
                env_file: env/prod.env
                image: mher/flower
                ports:
                - 5555:5555
                depends_on:
                - rabbitmq

volumes:
        db_volume:
