# Docker Compose Production Environments 
version : '3'
services:

        flask:
                image: modana-wallet-services
                entrypoint: ./scripts/build-prod.sh
                env_file: env/prod.env
                depends_on:
                - postgres
                - rabbitmq
                restart: always
                ports:
                - 6000:6000

        postgres:
                build:
                        context: dockerfiles/postgres/
                env_file: env/prod.env
                volumes:
                - "db_volume:/var/lib/postgresql/data"
                restart: always

        rabbitmq:
                build:
                        context: dockerfiles/rabbitmq/
                env_file: env/prod.env
                ports:
                - 16000:15672

        celery:
                env_file: env/prod.env
                image: modana-wallet-services
                entrypoint: make bank-worker
                depends_on:
                - rabbitmq
                - postgres

        celery2:
                env_file: env/prod.env
                image: modana-wallet-services
                entrypoint: make transaction-worker
                depends_on:
                - rabbitmq
                - postgres

        celery3:
                env_file: env/prod.env
                image: modana-wallet-services
                entrypoint: make payment-worker
                depends_on:
                - rabbitmq
                - postgres

        flower:
                env_file: env/prod.env
                image: mher/flower
                ports:
                - 6555:5555
                depends_on:
                - rabbitmq

        grpc:
                entrypoint: ./start.sh
                image: modana-wallet-grpc
                env_file: env/prod.env
                ports:
                - 6001:6001
                depends_on:
                - flask

        callback:
                entrypoint: ./start.sh
                image: modana-va-fake-grpc
                environment: 
                - GRPC_PORT=10000
                ports:
                - 10000:10000
                depends_on:
                - flask

volumes:
        db_volume:
