"""change some pk to string

Revision ID: 074a7a57e4f2
Revises: 2fd15bb8b02e
Create Date: 2018-10-26 05:11:56.114716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074a7a57e4f2'
down_revision = '2fd15bb8b02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_account', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_account', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
