"""added expiration etc

Revision ID: 0b3b71a2277c
Revises: a80f44e85b31
Create Date: 2018-10-19 14:32:16.104507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3b71a2277c'
down_revision = 'a80f44e85b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('expiration', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'api_key', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_key', type_='unique')
    op.drop_column('api_key', 'expiration')
    # ### end Alembic commands ###
