"""added label in wallet tables

Revision ID: 17798a476bf8
Revises: 30df92ac97f1
Create Date: 2019-02-06 21:35:33.520783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17798a476bf8'
down_revision = '30df92ac97f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('label', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'label')
    # ### end Alembic commands ###
