"""added external log tables

Revision ID: 1994149fc2e8
Revises: 98ea860bf45c
Create Date: 2018-10-24 15:40:18.360519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1994149fc2e8'
down_revision = '98ea860bf45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['source_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'wallet', ['destination_id'], ['id'])
    op.drop_column('transaction', 'source')
    op.drop_column('transaction', 'destination')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('destination', sa.INTEGER(), nullable=True))
    op.add_column('transaction', sa.Column('source', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['source'], ['id'])
    op.create_foreign_key(None, 'transaction', 'wallet', ['destination'], ['id'])
    op.drop_table('external_log')
    # ### end Alembic commands ###
