"""rename some column

Revision ID: 1b180b9e0751
Revises: 6e8f1f5d193c
Create Date: 2018-10-26 10:01:37.265054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b180b9e0751'
down_revision = '6e8f1f5d193c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_account', sa.Column('msisdn', sa.String(length=12), nullable=True))
    op.add_column('virtual_account', sa.Column('name', sa.String(length=144), nullable=True))
    op.drop_constraint('virtual_account_customer_email_key', 'virtual_account', type_='unique')
    op.drop_constraint('virtual_account_customer_name_key', 'virtual_account', type_='unique')
    op.drop_constraint('virtual_account_customer_phone_key', 'virtual_account', type_='unique')
    op.create_unique_constraint(None, 'virtual_account', ['msisdn'])
    op.drop_column('virtual_account', 'customer_name')
    op.drop_column('virtual_account', 'customer_phone')
    op.drop_column('virtual_account', 'customer_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_account', sa.Column('customer_email', sa.VARCHAR(length=144), autoincrement=False, nullable=True))
    op.add_column('virtual_account', sa.Column('customer_phone', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('virtual_account', sa.Column('customer_name', sa.VARCHAR(length=144), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'virtual_account', type_='unique')
    op.create_unique_constraint('virtual_account_customer_phone_key', 'virtual_account', ['customer_phone'])
    op.create_unique_constraint('virtual_account_customer_name_key', 'virtual_account', ['customer_name'])
    op.create_unique_constraint('virtual_account_customer_email_key', 'virtual_account', ['customer_email'])
    op.drop_column('virtual_account', 'name')
    op.drop_column('virtual_account', 'msisdn')
    # ### end Alembic commands ###
