"""add rtgs

Revision ID: 2a05af8feb46
Revises: 129505a613ae
Create Date: 2019-01-10 09:19:44.644041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a05af8feb46'
down_revision = '129505a613ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank', sa.Column('rtgs', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank', 'rtgs')
    # ### end Alembic commands ###
