"""rename last_balance to balance

Revision ID: 2eae96a38aaf
Revises: bf2526d1ff5c
Create Date: 2019-03-24 12:46:22.903890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2eae96a38aaf'
down_revision = 'bf2526d1ff5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bank', ['id'])
    op.create_unique_constraint(None, 'bank_account', ['id'])
    op.create_unique_constraint(None, 'payment', ['id'])
    op.create_unique_constraint(None, 'payment_channel', ['id'])
    op.add_column('transaction', sa.Column('balance', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'transaction', ['id'])
    op.drop_column('transaction', 'last_balance')
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'virtual_account', ['id'])
    op.create_unique_constraint(None, 'wallet', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='unique')
    op.drop_constraint(None, 'virtual_account', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('transaction', sa.Column('last_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='unique')
    op.drop_column('transaction', 'balance')
    op.drop_constraint(None, 'payment_channel', type_='unique')
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_constraint(None, 'bank_account', type_='unique')
    op.drop_constraint(None, 'bank', type_='unique')
    # ### end Alembic commands ###
