"""added resource & api name on external log tables

Revision ID: 2fd15bb8b02e
Revises: 6744177fdee0
Create Date: 2018-10-26 04:47:12.965449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd15bb8b02e'
down_revision = '6744177fdee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_log', sa.Column('api_name', sa.String(length=255), nullable=True))
    op.add_column('external_log', sa.Column('resource', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_log', 'resource')
    op.drop_column('external_log', 'api_name')
    # ### end Alembic commands ###
