"""added more table

Revision ID: 37eadf0a0f5e
Revises: 72320916972a
Create Date: 2018-10-20 19:11:01.882591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37eadf0a0f5e'
down_revision = '72320916972a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('trx_id', sa.Integer(), nullable=True),
    sa.Column('trx_amount', sa.Float(), nullable=True),
    sa.Column('billing_type', sa.String(length=1), nullable=True),
    sa.Column('customer_name', sa.String(length=144), nullable=True),
    sa.Column('customer_email', sa.String(length=144), nullable=True),
    sa.Column('customer_phone', sa.Integer(), nullable=True),
    sa.Column('virtual_account', sa.Integer(), nullable=True),
    sa.Column('datetime_expired', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_type'),
    sa.UniqueConstraint('customer_email'),
    sa.UniqueConstraint('customer_name'),
    sa.UniqueConstraint('customer_phone'),
    sa.UniqueConstraint('trx_amount'),
    sa.UniqueConstraint('trx_id'),
    sa.UniqueConstraint('virtual_account')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=144), nullable=True),
    sa.Column('msisdn', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=144), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('pin_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('msisdn')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('destination', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['destination'], ['wallet.id'], ),
    sa.ForeignKeyConstraint(['source'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('api_key', sa.Column('name', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'api_key', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_key', type_='unique')
    op.drop_column('api_key', 'name')
    op.drop_table('transaction')
    op.drop_table('wallet')
    op.drop_table('virtual_account')
    # ### end Alembic commands ###
