"""add unique column

Revision ID: 48ff7915d99a
Revises: 6d881136c354
Create Date: 2018-12-15 15:20:31.314944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ff7915d99a'
down_revision = '6d881136c354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bank_account', ['account_no'])
    op.create_unique_constraint(None, 'bank_account', ['name'])
    op.create_unique_constraint(None, 'bank_account', ['label'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_account', type_='unique')
    op.drop_constraint(None, 'bank_account', type_='unique')
    op.drop_constraint(None, 'bank_account', type_='unique')
    # ### end Alembic commands ###
