"""move to postgresql

Revision ID: 4d37bc2d1f64
Revises: 1994149fc2e8
Create Date: 2018-10-24 16:35:23.036744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d37bc2d1f64'
down_revision = '1994149fc2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('access_key', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_key'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('name')
    )
    op.create_table('external_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=144), nullable=True),
    sa.Column('msisdn', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=144), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pin_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('msisdn')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.Integer(), nullable=True),
    sa.Column('transfer_type', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['wallet.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('trx_id', sa.Integer(), nullable=True),
    sa.Column('trx_amount', sa.Float(), nullable=True),
    sa.Column('billing_type', sa.String(length=1), nullable=True),
    sa.Column('customer_name', sa.String(length=144), nullable=True),
    sa.Column('customer_email', sa.String(length=144), nullable=True),
    sa.Column('customer_phone', sa.Integer(), nullable=True),
    sa.Column('virtual_account', sa.Integer(), nullable=True),
    sa.Column('datetime_expired', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_type'),
    sa.UniqueConstraint('customer_email'),
    sa.UniqueConstraint('customer_name'),
    sa.UniqueConstraint('customer_phone'),
    sa.UniqueConstraint('trx_amount'),
    sa.UniqueConstraint('trx_id'),
    sa.UniqueConstraint('virtual_account')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_account')
    op.drop_table('transaction')
    op.drop_table('wallet')
    op.drop_table('external_log')
    op.drop_table('api_key')
    # ### end Alembic commands ###
