"""empty message

Revision ID: 5839f68a6139
Revises: e8f0b749beb0
Create Date: 2020-01-22 10:25:46.385640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5839f68a6139'
down_revision = 'e8f0b749beb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quota', sa.Column('reward_type', sa.String(length=255), nullable=True))
    op.add_column('quota_usage', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quota_usage', 'status')
    op.drop_column('quota', 'reward_type')
    # ### end Alembic commands ###
