"""added incorrect pin

Revision ID: 5e1149166703
Revises: 2eae96a38aaf
Create Date: 2019-03-25 17:01:32.044672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e1149166703'
down_revision = '2eae96a38aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incorrect_pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('wallet_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incorrect_pin')
    # ### end Alembic commands ###
