"""change datatype to BIGINT and remove unnecessary column

Revision ID: 6744177fdee0
Revises: 4d37bc2d1f64
Create Date: 2018-10-25 04:50:57.400962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6744177fdee0'
down_revision = '4d37bc2d1f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('virtual_account_virtual_account_key', 'virtual_account', type_='unique')
    op.drop_column('virtual_account', 'virtual_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_account', sa.Column('virtual_account', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('virtual_account_virtual_account_key', 'virtual_account', ['virtual_account'])
    # ### end Alembic commands ###
