"""added more column

Revision ID: 6d881136c354
Revises: 307caea1bded
Create Date: 2018-12-15 14:56:21.381909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d881136c354'
down_revision = '307caea1bded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('account_no', sa.String(length=24), nullable=True))
    op.add_column('bank_account', sa.Column('label', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_account', 'label')
    op.drop_column('bank_account', 'account_no')
    # ### end Alembic commands ###
