"""readd phone number

Revision ID: 6e8f1f5d193c
Revises: d5bab7474e17
Create Date: 2018-10-26 09:51:51.564375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8f1f5d193c'
down_revision = 'd5bab7474e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_account', sa.Column('customer_phone', sa.String(length=12), nullable=True))
    op.create_unique_constraint(None, 'virtual_account', ['customer_phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtual_account', type_='unique')
    op.drop_column('virtual_account', 'customer_phone')
    # ### end Alembic commands ###
