"""modify quota tables

Revision ID: 6f6ed2d3003e
Revises: 5839f68a6139
Create Date: 2020-01-22 17:16:28.340865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f6ed2d3003e'
down_revision = '5839f68a6139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('transaction_transaction_link_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'transaction', ['parent_id'], ['id'])
    op.drop_column('transaction', 'transaction_link_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_link_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_transaction_link_id_fkey', 'transaction', 'transaction', ['transaction_link_id'], ['id'])
    op.drop_column('transaction', 'parent_id')
    # ### end Alembic commands ###
