"""added more tables

Revision ID: 72320916972a
Revises: ef30b4638a98
Create Date: 2018-10-20 19:08:57.092109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72320916972a'
down_revision = 'ef30b4638a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('trx_id', sa.Integer(), nullable=True),
    sa.Column('trx_amount', sa.Float(), nullable=True),
    sa.Column('billing_type', sa.String(length=1), nullable=True),
    sa.Column('customer_name', sa.String(length=144), nullable=True),
    sa.Column('customer_email', sa.String(length=144), nullable=True),
    sa.Column('customer_phone', sa.Integer(), nullable=True),
    sa.Column('virtual_account', sa.Integer(), nullable=True),
    sa.Column('datetime_expired', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_type'),
    sa.UniqueConstraint('customer_email'),
    sa.UniqueConstraint('customer_name'),
    sa.UniqueConstraint('customer_phone'),
    sa.UniqueConstraint('trx_amount'),
    sa.UniqueConstraint('trx_id'),
    sa.UniqueConstraint('virtual_account')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('destination', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['destination'], ['wallet.id'], ),
    sa.ForeignKeyConstraint(['source'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('wallet', 'wallet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('wallet_id', sa.INTEGER(), nullable=True))
    op.drop_table('transaction')
    op.drop_table('virtual_account')
    # ### end Alembic commands ###
