"""remove bank uniq

Revision ID: 7bd64983d146
Revises: e083ddb1ec74
Create Date: 2019-03-12 11:03:33.189541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd64983d146'
down_revision = 'e083ddb1ec74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bank_account_label_key', 'bank_account', type_='unique')
    op.drop_constraint('bank_account_name_key', 'bank_account', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bank_account_name_key', 'bank_account', ['name'])
    op.create_unique_constraint('bank_account_label_key', 'bank_account', ['label'])
    # ### end Alembic commands ###
