"""2019-04-12

Revision ID: 853ffb58826e
Revises: b6100679d288
Create Date: 2019-04-12 14:36:57.208496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853ffb58826e'
down_revision = 'b6100679d288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plan_payment_plan_id_fkey', 'plan', type_='foreignkey')
    op.create_foreign_key(None, 'plan', 'payment_plan', ['payment_plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan', type_='foreignkey')
    op.create_foreign_key('plan_payment_plan_id_fkey', 'plan', 'payment_plan', ['payment_plan_id'], ['id'])
    # ### end Alembic commands ###
