"""restructure some table and add timestamp

Revision ID: 916a1bc4f9bc
Revises: 37eadf0a0f5e
Create Date: 2018-10-22 11:30:01.121964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916a1bc4f9bc'
down_revision = '37eadf0a0f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'api_key', ['name'])
    op.add_column('transaction', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('transaction_type', sa.Boolean(), nullable=True))
    op.drop_column('transaction', 'balance')
    op.add_column('wallet', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('wallet', 'create_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('create_at', sa.DATETIME(), nullable=True))
    op.drop_column('wallet', 'created_at')
    op.add_column('transaction', sa.Column('balance', sa.FLOAT(), nullable=True))
    op.drop_column('transaction', 'transaction_type')
    op.drop_column('transaction', 'created_at')
    op.drop_column('transaction', 'amount')
    op.drop_constraint(None, 'api_key', type_='unique')
    op.drop_column('api_key', 'created_at')
    # ### end Alembic commands ###
