"""added transfer_type

Revision ID: 98ea860bf45c
Revises: fddb5b441261
Create Date: 2018-10-24 13:44:12.705876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ea860bf45c'
down_revision = 'fddb5b441261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transfer_type', sa.Boolean(), nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['source_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'wallet', ['destination_id'], ['id'])
    op.drop_column('transaction', 'destination')
    op.drop_column('transaction', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('source', sa.INTEGER(), nullable=True))
    op.add_column('transaction', sa.Column('destination', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['destination'], ['id'])
    op.create_foreign_key(None, 'transaction', 'wallet', ['source'], ['id'])
    op.drop_column('transaction', 'transfer_type')
    # ### end Alembic commands ###
