"""added va status

Revision ID: 99f1a0189b62
Revises: 830a476c2bba
Create Date: 2018-10-26 13:35:18.768672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f1a0189b62'
down_revision = '830a476c2bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_account', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_account', 'status')
    # ### end Alembic commands ###
