"""added new structure

Revision ID: a80f44e85b31
Revises: 9b769a86bbb3
Create Date: 2018-10-18 12:26:51.504759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80f44e85b31'
down_revision = '9b769a86bbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key', 'key', new_column_name='access_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_key', type_='unique')
    op.drop_column('api_key', 'name')
    # ### end Alembic commands ###
