"""newer

Revision ID: aad9163d932f
Revises: e2b98a7d6269
Create Date: 2019-02-21 11:47:01.997247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad9163d932f'
down_revision = 'e2b98a7d6269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.drop_constraint('log_credit_payment_id_fkey', 'log', type_='foreignkey')
    op.drop_constraint('log_debit_payment_id_fkey', 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'payment', ['payment_id'], ['id'])
    op.drop_column('log', 'debit_payment_id')
    op.drop_column('log', 'credit_payment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('credit_payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('log', sa.Column('debit_payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key('log_debit_payment_id_fkey', 'log', 'payment', ['debit_payment_id'], ['id'])
    op.create_foreign_key('log_credit_payment_id_fkey', 'log', 'payment', ['credit_payment_id'], ['id'])
    op.drop_column('log', 'payment_id')
    # ### end Alembic commands ###
