"""remove phone number

Revision ID: d5bab7474e17
Revises: 64cd17bc61dc
Create Date: 2018-10-26 09:50:48.716011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bab7474e17'
down_revision = '64cd17bc61dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('virtual_account_customer_phone_key', 'virtual_account', type_='unique')
    op.drop_column('virtual_account', 'customer_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_account', sa.Column('customer_phone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('virtual_account_customer_phone_key', 'virtual_account', ['customer_phone'])
    # ### end Alembic commands ###
