"""added username & password for access key

Revision ID: dbf32dd299d8
Revises: a61b5584460a
Create Date: 2018-10-30 15:12:27.554911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf32dd299d8'
down_revision = 'a61b5584460a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('api_key', sa.Column('username', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'api_key', ['password_hash'])
    op.create_unique_constraint(None, 'api_key', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_key', type_='unique')
    op.drop_constraint(None, 'api_key', type_='unique')
    op.drop_column('api_key', 'username')
    op.drop_column('api_key', 'password_hash')
    # ### end Alembic commands ###
