"""remove balance

Revision ID: df44268fa746
Revises: 122e5412a62a
Create Date: 2019-01-10 13:05:34.539999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df44268fa746'
down_revision = '122e5412a62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'balance')
    # ### end Alembic commands ###
