"""new tables

Revision ID: e4a97ca74c79
Revises: e42962d7f051
Create Date: 2018-11-07 06:04:45.083795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a97ca74c79'
down_revision = 'e42962d7f051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=144), nullable=True),
    sa.Column('name', sa.String(length=144), nullable=True),
    sa.Column('msisdn', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=144), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('msisdn')
    )
    op.drop_column('virtual_account', 'bank_id')
    op.drop_column('virtual_account', 'va_type')
    op.add_column('wallet', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('wallet_email_key', 'wallet', type_='unique')
    op.drop_constraint('wallet_msisdn_key', 'wallet', type_='unique')
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'])
    op.drop_column('wallet', 'password_hash')
    op.drop_column('wallet', 'msisdn')
    op.drop_column('wallet', 'name')
    op.drop_column('wallet', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('email', sa.VARCHAR(length=144), autoincrement=False, nullable=True))
    op.add_column('wallet', sa.Column('name', sa.VARCHAR(length=144), autoincrement=False, nullable=True))
    op.add_column('wallet', sa.Column('msisdn', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('wallet', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.create_unique_constraint('wallet_msisdn_key', 'wallet', ['msisdn'])
    op.create_unique_constraint('wallet_email_key', 'wallet', ['email'])
    op.drop_column('wallet', 'user_id')
    op.add_column('virtual_account', sa.Column('va_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('virtual_account', sa.Column('bank_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('user')
    # ### end Alembic commands ###
