"""rename fields for quota

Revision ID: e8f0b749beb0
Revises: 4ad9aec165d9
Create Date: 2020-01-20 10:48:35.286276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8f0b749beb0'
down_revision = '4ad9aec165d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quota', sa.Column('end_valid', sa.DateTime(), nullable=True))
    op.add_column('quota', sa.Column('quota_type', sa.String(length=255), nullable=True))
    op.add_column('quota', sa.Column('start_valid', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'quota', ['id'])
    op.drop_column('quota', 'valid_until')
    op.create_unique_constraint(None, 'quota_usage', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quota_usage', type_='unique')
    op.add_column('quota', sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quota', type_='unique')
    op.drop_column('quota', 'start_valid')
    op.drop_column('quota', 'quota_type')
    op.drop_column('quota', 'end_valid')
    # ### end Alembic commands ###
