"""added api_type

Revision ID: e9a664461ba1
Revises: 5a845fea60b3
Create Date: 2018-11-27 10:16:43.066604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a664461ba1'
down_revision = '5a845fea60b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_log', sa.Column('api_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_log', 'api_type')
    # ### end Alembic commands ###
