"""update master_transaction tables

Revision ID: f7871a95d031
Revises: 9df2cb2746a4
Create Date: 2019-01-21 17:06:01.305729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7871a95d031'
down_revision = '9df2cb2746a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_transaction', sa.Column('credit_transaction_id', sa.String(), nullable=True))
    op.add_column('master_transaction', sa.Column('debit_transaction_id', sa.String(), nullable=True))
    op.drop_constraint('master_transaction_transaction_id_fkey', 'master_transaction', type_='foreignkey')
    op.create_foreign_key(None, 'master_transaction', 'transaction', ['debit_transaction_id'], ['id'])
    op.create_foreign_key(None, 'master_transaction', 'transaction', ['credit_transaction_id'], ['id'])
    op.drop_column('master_transaction', 'transaction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_transaction', sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'master_transaction', type_='foreignkey')
    op.drop_constraint(None, 'master_transaction', type_='foreignkey')
    op.create_foreign_key('master_transaction_transaction_id_fkey', 'master_transaction', 'transaction', ['transaction_id'], ['id'])
    op.drop_column('master_transaction', 'debit_transaction_id')
    op.drop_column('master_transaction', 'credit_transaction_id')
    # ### end Alembic commands ###
