"""new

Revision ID: fddb5b441261
Revises: 252bd8e375df
Create Date: 2018-10-23 10:33:36.220862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddb5b441261'
down_revision = '252bd8e375df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('destination_id', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('source_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['source_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'wallet', ['destination_id'], ['id'])
    op.drop_column('transaction', 'destination')
    op.drop_column('transaction', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('source', sa.INTEGER(), nullable=True))
    op.add_column('transaction', sa.Column('destination', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['destination'], ['id'])
    op.create_foreign_key(None, 'transaction', 'wallet', ['source'], ['id'])
    op.drop_column('transaction', 'source_id')
    op.drop_column('transaction', 'destination_id')
    # ### end Alembic commands ###
